spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://10.116.2.142/sell?characterEncoding=utf-8&useSSL=false
#   url: jdbc:mysql://192.168.1.8/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true